"""add parent_id to messages

Revision ID: 309ddacd7043
Revises: 8c2499996555
Create Date: 2026-05-22 02:28:33.116987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309ddacd7043'
down_revision = '8c2499996555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_parent_id'), ['parent_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('messages_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_parent_id_fkey'), 'messages', ['parent_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_messages_parent_id'))

    # ### end Alembic commands ###
