"""Add created_at and workspace_id to PinnedItem

Revision ID: 41049cd0a899
Revises: 
Create Date: 2026-05-15 22:13:11.971474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41049cd0a899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('attachments_message_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'messages', ['message_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_participants_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('chat_participants_chat_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chats', ['chat_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chats_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chats_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cities_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('forwarded_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forwarded_messages_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_chat_created_at', ['chat_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_workspace_id'), ['workspace_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('messages_chat_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chats', ['chat_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pinned_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pinned_items_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('pinned_at')

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_assignments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('allowed_locations',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='allowed_locations::json')
        batch_op.alter_column('allowed_clients',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='allowed_clients::json')

    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_workspace_members_workspace'))
        batch_op.create_index(batch_op.f('ix_workspace_members_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspaces_created_by_id'), ['created_by_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_workspaces_created_at'))

    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_members_created_at'))
        batch_op.create_index(batch_op.f('idx_workspace_members_workspace'), ['workspace_id'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('allowed_clients',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('allowed_locations',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_workspace_id'))

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_assignments_created_at'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('pinned_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_pinned_items_created_at'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_chat_id_fkey'), 'chats', ['chat_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_messages_workspace_id'))
        batch_op.drop_index('idx_message_chat_created_at')

    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_created_at'))

    with op.batch_alter_table('forwarded_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forwarded_messages_created_at'))

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_created_at'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_chats_created_at'))

    with op.batch_alter_table('chat_participants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_participants_chat_id_fkey'), 'chats', ['chat_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_chat_participants_created_at'))

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attachments_message_id_fkey'), 'messages', ['message_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_attachments_created_at'))

    # ### end Alembic commands ###
