"""Add thumbnail_path and optimized_path to Attachment

Revision ID: 8c2499996555
Revises: 41049cd0a899
Create Date: 2026-05-15 22:40:24.502578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2499996555'
down_revision = '41049cd0a899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('optimized_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_column('optimized_path')
        batch_op.drop_column('thumbnail_path')

    # ### end Alembic commands ###
